# tasks file for fail2ban
---
- name: install
  apt:
    name: fail2ban
    state: latest
    update_cache: true
    cache_valid_time: 3600
  tags: [configuration, fail2ban, fail2ban-install]

- name: update configuration file - /etc/fail2ban/fail2ban.conf
  template:
    src: etc/fail2ban/fail2ban.conf.j2
    dest: /etc/fail2ban/fail2ban.conf
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban
  tags: [configuration, fail2ban, fail2ban-configuration]

- name: update configuration file - /etc/fail2ban/jail.local
  template:
    src: etc/fail2ban/jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban
  tags: [configuration, fail2ban, fail2ban-configuration]

- name: copy filters
  copy:
    src: "{{ fail2ban_filterd_path }}"
    dest: /etc/fail2ban/filter.d/
    owner: root
    group: root
    mode: 0644
  when: fail2ban_filterd_path is defined
  notify: restart fail2ban
  tags: [configuration, fail2ban, fail2ban-filters]

- name: start and enable service
  service:
    name: fail2ban
    state: started
    enabled: yes
  tags: [configuration, fail2ban, fail2ban-start-enable-service]
